# Load dataset

In [10]:
import csv
import numpy
from sklearn import datasets
filename = 'facial_keypoints.csv'
raw_data= open(filename,'r')
reader=csv.reader(raw_data, delimiter=',',quoting=csv.QUOTE_NONE)
x=list(reader)
data = numpy.array(x)
print(data.shape)


(7050, 30)


In [11]:
#load csv using pandas
#from pandas import read_csv
import pandas as pd
filename = 'facial_keypoints.csv'
#names=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']
data =pd.read_csv(filename)
data.set_index('left_eye_center_x',inplace=True)
new=data.interpolate()
print(new.shape)
print(new.dtypes)
peek=(new.head(20))
print(new)

(7049, 29)
left_eye_center_y            float64
right_eye_center_x           float64
right_eye_center_y           float64
left_eye_inner_corner_x      float64
left_eye_inner_corner_y      float64
left_eye_outer_corner_x      float64
left_eye_outer_corner_y      float64
right_eye_inner_corner_x     float64
right_eye_inner_corner_y     float64
right_eye_outer_corner_x     float64
right_eye_outer_corner_y     float64
left_eyebrow_inner_end_x     float64
left_eyebrow_inner_end_y     float64
left_eyebrow_outer_end_x     float64
left_eyebrow_outer_end_y     float64
right_eyebrow_inner_end_x    float64
right_eyebrow_inner_end_y    float64
right_eyebrow_outer_end_x    float64
right_eyebrow_outer_end_y    float64
nose_tip_x                   float64
nose_tip_y                   float64
mouth_left_corner_x          float64
mouth_left_corner_y          float64
mouth_right_corner_x         float64
mouth_right_corner_y         float64
mouth_center_top_lip_x       float64
mouth_center_top_lip_y     

# feature Extraction

In [12]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas as pd
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import Imputer
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)
# load data
filename = 'facial_keypoints.csv'
names = ['left_eye_center_x','left_eye_center_y','right_eye_center_x','right_eye_center_y','left_eye_inner_corner_x','left_eye_inner_corner_y','left_eye_outer_corner_x','left_eye_outer_corner_y','right_eye_inner_corner_x','right_eye_inner_corner_y','right_eye_outer_corner_x','right_eye_outer_corner_y','left_eyebrow_inner_end_x','left_eyebrow_inner_end_y','left_eyebrow_outer_end_x','left_eyebrow_outer_end_y','right_eyebrow_inner_end_x','right_eyebrow_inner_end_y','right_eyebrow_outer_end_x','right_eyebrow_outer_end_y','nose_tip_x','nose_tip_y','mouth_left_corner_x','mouth_left_corner_y','mouth_right_corner_x','mouth_right_corner_y','mouth_center_top_lip_x','mouth_center_top_lip_y','mouth_center_bottom_lip_x','mouth_center_bottom_lip_y']
data= read_csv(filename, names=names, delimiter=",", header=None)

data['left_eye_center_x']= pd.to_numeric(data['left_eye_center_x'],errors='coerce')
data['left_eye_center_y']= pd.to_numeric(data['left_eye_center_y'],errors='coerce')
data['right_eye_center_x']= pd.to_numeric(data['right_eye_center_x'],errors='coerce')
data['right_eye_center_y']= pd.to_numeric(data['right_eye_center_y'],errors='coerce')
data['left_eye_inner_corner_x']= pd.to_numeric(data['left_eye_inner_corner_x'],errors='coerce')
data['left_eye_inner_corner_y']= pd.to_numeric(data['left_eye_inner_corner_y'],errors='coerce')
data['left_eye_outer_corner_x']= pd.to_numeric(data['left_eye_outer_corner_x'],errors='coerce')
data['left_eye_outer_corner_y']= pd.to_numeric(data['left_eye_outer_corner_y'],errors='coerce')
data['right_eye_inner_corner_x']= pd.to_numeric(data['right_eye_inner_corner_x'],errors='coerce')
data['right_eye_inner_corner_y']= pd.to_numeric(data['right_eye_inner_corner_y'],errors='coerce')
data['right_eye_outer_corner_x']= pd.to_numeric(data['right_eye_outer_corner_x'],errors='coerce')
data['right_eye_outer_corner_y']= pd.to_numeric(data['right_eye_outer_corner_y'],errors='coerce')
data['left_eyebrow_inner_end_x']= pd.to_numeric(data['left_eyebrow_inner_end_x'],errors='coerce')
data['left_eyebrow_inner_end_y']= pd.to_numeric(data['left_eyebrow_inner_end_y'],errors='coerce')
data['left_eyebrow_outer_end_x']= pd.to_numeric(data['left_eyebrow_outer_end_x'],errors='coerce')
data['left_eyebrow_outer_end_y']= pd.to_numeric(data['left_eyebrow_outer_end_y'],errors='coerce')
data['right_eyebrow_inner_end_x']= pd.to_numeric(data['right_eyebrow_inner_end_x'],errors='coerce')
data['right_eyebrow_inner_end_y']= pd.to_numeric(data['right_eyebrow_inner_end_y'],errors='coerce')
data['right_eyebrow_outer_end_x']= pd.to_numeric(data['right_eyebrow_outer_end_x'],errors='coerce')
data['right_eyebrow_outer_end_y']= pd.to_numeric(data['right_eyebrow_outer_end_y'],errors='coerce')
data['nose_tip_x']= pd.to_numeric(data['nose_tip_x'],errors='coerce')
data['nose_tip_y']= pd.to_numeric(data['nose_tip_y'],errors='coerce')
data['mouth_left_corner_x']= pd.to_numeric(data['mouth_left_corner_x'],errors='coerce')
data['mouth_left_corner_y']= pd.to_numeric(data['mouth_left_corner_y'],errors='coerce')
data['mouth_right_corner_x']= pd.to_numeric(data['mouth_right_corner_x'],errors='coerce')
data['mouth_right_corner_y']= pd.to_numeric(data['mouth_right_corner_y'],errors='coerce')
data['mouth_center_top_lip_x']= pd.to_numeric(data['mouth_center_top_lip_x'],errors='coerce')
data['mouth_center_top_lip_y']= pd.to_numeric(data['mouth_center_top_lip_y'],errors='coerce')
data['mouth_center_bottom_lip_x']= pd.to_numeric(data['mouth_center_bottom_lip_x'],errors='coerce')
data['mouth_center_bottom_lip_y']= pd.to_numeric(data['mouth_center_bottom_lip_y'],errors='coerce')



In [13]:
array = new.values
X = array[:,0:8]
Y = array[:,8].astype(int)
pd.set_option('display.expand_frame_repr', False)
 

In [14]:
test = SelectKBest(score_func=chi2, k=8)

fit = test.fit(X,Y)

# summarize scores
set_printoptions(precision=3)
print('-------------------- Chi square test ------------------------')
print(names)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

-------------------- Chi square test ------------------------
['left_eye_center_x', 'left_eye_center_y', 'right_eye_center_x', 'right_eye_center_y', 'left_eye_inner_corner_x', 'left_eye_inner_corner_y', 'left_eye_outer_corner_x', 'left_eye_outer_corner_y', 'right_eye_inner_corner_x', 'right_eye_inner_corner_y', 'right_eye_outer_corner_x', 'right_eye_outer_corner_y', 'left_eyebrow_inner_end_x', 'left_eyebrow_inner_end_y', 'left_eyebrow_outer_end_x', 'left_eyebrow_outer_end_y', 'right_eyebrow_inner_end_x', 'right_eyebrow_inner_end_y', 'right_eyebrow_outer_end_x', 'right_eyebrow_outer_end_y', 'nose_tip_x', 'nose_tip_y', 'mouth_left_corner_x', 'mouth_left_corner_y', 'mouth_right_corner_x', 'mouth_right_corner_y', 'mouth_center_top_lip_x', 'mouth_center_top_lip_y', 'mouth_center_bottom_lip_x', 'mouth_center_bottom_lip_y']
[187.689 104.159 386.365  68.496 257.836  58.727 400.903  84.976]
[[39.002 30.227 36.422 59.582 39.647 73.13  39.97  36.357]
 [34.97  29.949 33.449 58.856 35.274 70.723 36

In [15]:
print('-------------------- Recursive Feature Elimination ------------------------')

model = LogisticRegression()
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

-------------------- Recursive Feature Elimination ------------------------
Num Features: 3
Selected Features: [False False False  True  True False  True False]
Feature Ranking: [4 6 3 1 1 2 1 5]


In [16]:
print('-------------------- Principal Componenet Ananlysis ------------------------')
pca = PCA(n_components=2 )
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

-------------------- Principal Componenet Ananlysis ------------------------
Explained Variance: [0.327 0.213]
[[ 0.708  0.45   0.514  0.024  0.116  0.005  0.098  0.095]
 [ 0.176 -0.795  0.401 -0.122  0.202 -0.111  0.264 -0.196]]


In [17]:
print('-------------------- Feature Importance ------------------------')

model = ExtraTreesClassifier()
model.fit(X, Y)
print(model.feature_importances_)

-------------------- Feature Importance ------------------------
[0.065 0.057 0.141 0.102 0.154 0.106 0.262 0.113]
