In [2]:
#load csv using pandas
#from pandas import read_csv
import pandas as pd
filename = 'facial_keypoints.csv'
#names=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']
data =pd.read_csv(filename)
data.set_index('left_eye_center_x',inplace=True)
new=data.interpolate()
print(data.shape)
print(data.dtypes)
peek=(data.head(20))
print(new)

(7049, 29)
left_eye_center_y            float64
right_eye_center_x           float64
right_eye_center_y           float64
left_eye_inner_corner_x      float64
left_eye_inner_corner_y      float64
left_eye_outer_corner_x      float64
left_eye_outer_corner_y      float64
right_eye_inner_corner_x     float64
right_eye_inner_corner_y     float64
right_eye_outer_corner_x     float64
right_eye_outer_corner_y     float64
left_eyebrow_inner_end_x     float64
left_eyebrow_inner_end_y     float64
left_eyebrow_outer_end_x     float64
left_eyebrow_outer_end_y     float64
right_eyebrow_inner_end_x    float64
right_eyebrow_inner_end_y    float64
right_eyebrow_outer_end_x    float64
right_eyebrow_outer_end_y    float64
nose_tip_x                   float64
nose_tip_y                   float64
mouth_left_corner_x          float64
mouth_left_corner_y          float64
mouth_right_corner_x         float64
mouth_right_corner_y         float64
mouth_center_top_lip_x       float64
mouth_center_top_lip_y     

In [3]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer
import pandas as pd
filename = 'facial_keypoints.csv'
names = ['left_eye_center_x','left_eye_center_y','right_eye_center_x','right_eye_center_y','left_eye_inner_corner_x','left_eye_inner_corner_y','left_eye_outer_corner_x','left_eye_outer_corner_y','right_eye_inner_corner_x','right_eye_inner_corner_y','right_eye_outer_corner_x','right_eye_outer_corner_y','left_eyebrow_inner_end_x','left_eyebrow_inner_end_y','left_eyebrow_outer_end_x','left_eyebrow_outer_end_y','right_eyebrow_inner_end_x','right_eyebrow_inner_end_y','right_eyebrow_outer_end_x','right_eyebrow_outer_end_y','nose_tip_x','nose_tip_y','mouth_left_corner_x','mouth_left_corner_y','mouth_right_corner_x','mouth_right_corner_y','mouth_center_top_lip_x','mouth_center_top_lip_y','mouth_center_bottom_lip_x','mouth_center_bottom_lip_y']
data= read_csv(filename, names=names, delimiter=",", header=None)
data['left_eye_center_x']= pd.to_numeric(data['left_eye_center_x'],errors='coerce')
data['left_eye_center_y']= pd.to_numeric(data['left_eye_center_y'],errors='coerce')
data['right_eye_center_x']= pd.to_numeric(data['right_eye_center_x'],errors='coerce')
data['right_eye_center_y']= pd.to_numeric(data['right_eye_center_y'],errors='coerce')
data['left_eye_inner_corner_x']= pd.to_numeric(data['left_eye_inner_corner_x'],errors='coerce')
data['left_eye_inner_corner_y']= pd.to_numeric(data['left_eye_inner_corner_y'],errors='coerce')
data['left_eye_outer_corner_x']= pd.to_numeric(data['left_eye_outer_corner_x'],errors='coerce')
data['left_eye_outer_corner_y']= pd.to_numeric(data['left_eye_outer_corner_y'],errors='coerce')
data['right_eye_inner_corner_x']= pd.to_numeric(data['right_eye_inner_corner_x'],errors='coerce')
data['right_eye_inner_corner_y']= pd.to_numeric(data['right_eye_inner_corner_y'],errors='coerce')
data['right_eye_outer_corner_x']= pd.to_numeric(data['right_eye_outer_corner_x'],errors='coerce')
data['right_eye_outer_corner_y']= pd.to_numeric(data['right_eye_outer_corner_y'],errors='coerce')
data['left_eyebrow_inner_end_x']= pd.to_numeric(data['left_eyebrow_inner_end_x'],errors='coerce')
data['left_eyebrow_inner_end_y']= pd.to_numeric(data['left_eyebrow_inner_end_y'],errors='coerce')
data['left_eyebrow_outer_end_x']= pd.to_numeric(data['left_eyebrow_outer_end_x'],errors='coerce')
data['left_eyebrow_outer_end_y']= pd.to_numeric(data['left_eyebrow_outer_end_y'],errors='coerce')
data['right_eyebrow_inner_end_x']= pd.to_numeric(data['right_eyebrow_inner_end_x'],errors='coerce')
data['right_eyebrow_inner_end_y']= pd.to_numeric(data['right_eyebrow_inner_end_y'],errors='coerce')
data['right_eyebrow_outer_end_x']= pd.to_numeric(data['right_eyebrow_outer_end_x'],errors='coerce')
data['right_eyebrow_outer_end_y']= pd.to_numeric(data['right_eyebrow_outer_end_y'],errors='coerce')
data['nose_tip_x']= pd.to_numeric(data['nose_tip_x'],errors='coerce')
data['nose_tip_y']= pd.to_numeric(data['nose_tip_y'],errors='coerce')
data['mouth_left_corner_x']= pd.to_numeric(data['mouth_left_corner_x'],errors='coerce')
data['mouth_left_corner_y']= pd.to_numeric(data['mouth_left_corner_y'],errors='coerce')
data['mouth_right_corner_x']= pd.to_numeric(data['mouth_right_corner_x'],errors='coerce')
data['mouth_right_corner_y']= pd.to_numeric(data['mouth_right_corner_y'],errors='coerce')
data['mouth_center_top_lip_x']= pd.to_numeric(data['mouth_center_top_lip_x'],errors='coerce')
data['mouth_center_top_lip_y']= pd.to_numeric(data['mouth_center_top_lip_y'],errors='coerce')
data['mouth_center_bottom_lip_x']= pd.to_numeric(data['mouth_center_bottom_lip_x'],errors='coerce')
data['mouth_center_bottom_lip_y']= pd.to_numeric(data['mouth_center_bottom_lip_y'],errors='coerce')


In [8]:
array=new.values
X=array[1:,0:8]
Y=array[:,8]
pd.set_option('display.expand_frame_repr', False)

In [9]:
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
# summarize transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[0.42 0.35 0.38 0.61 0.21 0.64 0.26 0.47]
 [0.42 0.36 0.4  0.62 0.23 0.64 0.26 0.49]
 [0.45 0.37 0.43 0.63 0.3  0.66 0.32 0.49]
 [0.48 0.37 0.44 0.6  0.32 0.66 0.36 0.48]
 [0.49 0.34 0.43 0.67 0.33 0.73 0.39 0.47]]


In [10]:
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[-0.85  -0.116 -1.493 -0.24  -0.887 -1.546  0.26  -0.848]
 [-0.869  0.193 -1.012  0.123 -0.224 -1.412  0.321  0.334]
 [-0.123  0.556 -0.236  0.509  1.555 -0.732  1.267  0.291]
 [ 0.626  0.628  0.022 -0.43   1.868 -0.629  1.957 -0.166]
 [ 0.736 -0.365 -0.136  2.379  2.215  1.612  2.547 -0.585]]


In [11]:
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[0.28  0.24  0.268 0.472 0.283 0.567 0.29  0.289]
 [0.276 0.244 0.276 0.469 0.287 0.561 0.287 0.298]
 [0.285 0.245 0.285 0.46  0.3   0.554 0.294 0.288]
 [0.301 0.245 0.289 0.446 0.301 0.552 0.303 0.281]
 [0.295 0.215 0.277 0.464 0.296 0.568 0.304 0.269]]


In [14]:
binarizer = Binarizer(threshold=0.4).fit(X)
binaryX = binarizer.transform(X)
# summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
